version: "3.8"
services:
  node_backend:
    restart: always
    depends_on: 
      - db
    image: "docker.pkg.github.com/pongroyale/gameserver/node_backend"
    ports:
      - "3001:3001"
    env_file: 
      - .env
  db:
    image: "postgres:12"
    restart: always
    volumes:
      - ./db/postgres-data:/var/lib/postgresql
    env_file: 
      - .env
      